replicaCount: 1

image:
  repository: "anonrig/docs"
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: "docs-registry"
nameOverride: "docs"
fullnameOverride: "docs"

serviceAccount:
  create: true
  annotations: {}
  name: "docs-account"

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: docs.yagiz.co
      paths:
      - path: /
        backend:
          serviceName: docs
          servicePort: 3000
  tls:
   - secretName: "docs-tls"
     hosts:
       - docs.yagiz.co

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

application:
  secretName: "docs-environment"
